[package]
name = "michromer"
description = "This is a small library to interact with the stockfighter simulation challenges."
version = "0.1.1"
authors = ["Elliott Clark <elliott@fb.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/elliottneilclark/michromer"

[dependencies]
hyper = "0.9.6"
rustc-serialize = "0.3.19"
log = "0.3.6"


